spring:
  application:
    name: system
    # 数据库配置
  datasource:
    url: jdbc:postgresql://8.152.98.162:5432/mes_system
    username: postgres
    password: postgre_ziwen
    driver-class-name: org.postgresql.Driver
    #redis配置
  data:
    redis:
      host: 8.152.98.162
      port: 6379
      password:       mvn clean      mvn clean
      database: 0
      timeout: 10000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml   # 如果有XML文件
  type-aliases-package: com.mes.system.entity     # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true           # 下划线转驼峰

  
  